dic = {"lek": "L",
       "peso": "$",
       "dram": "Դ",
       "dollar": "$",
       "manat": "ман",
       "ruble": "Br",
       "boliviano": "Bs.",
       "pula": "P",
       "real": "R$",
       "lev": "Лв.",
       "riel": "៛",
       "yuan": "¥",
       "colon": "₡",
       "kuna": "kn",
       "koruna": "Kč",
       "krone": "kr",
       "pound": "£",

       "euro": "€",
       "cedi": "¢",
       "guatemala": "Q",
       "franc": "₣",
       "lempira": "L",
       "forint": "Ft",
       "rupiah": "Rp",
       "rupees": "₹",
       "krona": "kr",
       "shekel": "₪",
       "yen": "¥",
       "tenge": "лв",
       "shilling": "ksh",
       "dinar": "د.ك",
       "kwacha": "MK",
       "ringgit": "RM",
       "dirham": "DH",
       "rupee": "Rs",
       "omani": "ر.ع.",
       "sol": "S/.",
       "zloty": "zł",
       "riyal": "QR",
       "leu": "L",



       "rand": "R",

       "baht": "฿",
       "lira": "₺",
       "hryvnia": "₴",
       "sterling": "£",
       "uzbekistan": "UZS",
       "fuerte": "Bs F",
       "dong": "₫",

       }
